# -*- coding: utf-8 -*-
"""matplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JK3-Q1RjtuMkS3HFKAOzervd8jv_KFcB
"""

import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

x =np.arange(0,10)

x

y = x*2
y

plt.plot(x,y)
plt.show
plt.title("String Title ")
plt.xlabel("x label")
plt.ylabel("y label")
plt.xlim(0,12)
plt.ylim(0,20)
plt.savefig('example.png')

a = np.linspace(0,20,11)
a

b = a*2
b

x =np.arange(0,11)
x

y = x *2

fig = plt.figure()
axes = fig.add_axes([0,0,1,1])
axes.plot(a,b)

axes.set_title("String Title ")
axes.set_xlabel("x label")
axes.set_ylabel("y label")
axes.set_xlim(0,12)
axes.set_ylim(0,20)



# small
axes2 = fig.add_axes([0.2,0.2,0.3,0.3])
axes.plot(x,y)
axes2.set_title("String Title ")
axes2.set_xlabel("x label")
axes2.set_ylabel("y label")
axes2.set_xlim(0,2)
axes2.set_ylim(0,4)

a = np.arange(10,21)
b = np.arange(20,31)



fig = plt.figure(figsize =(2,3),dpi=200)
axes1 = fig.add_axes([0,0,1,1])
axes1.plot(a,b)

x= np.arange(0,20)
y = x*2

a = np.linspace(0,10,11)
b = a **4
b

fig , axes = plt.subplots(nrows = 2 , ncols =2)
axes[0][0].plot(x,y)
axes[0][1].plot(a,b)
axes[1][0].plot(b,a)
as2 = axes[1][1].plot(y,x)
as2=axes[0][0]
as2.set_xlabel("Cade")

plt.tight_layout()
# fig.subplots_adjust(wspace=0.7, hspace = 0.9)
fig.suptitle('Figure level', fontsize = 1);

x =  np.linspace(0,11,10)
fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
ax.plot(x,x, label = "x vs x", color = '#93BD55',lw=2, marker='o')
ax.plot(x**4,label = "x vs x^4", color = 'red', lw=3,marker = '*', markersize=20)
ax.legend(loc=(0,0.88))