# -*- coding: utf-8 -*-
"""Operation_Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wh-oeEPHNOW1WTplxv4uGlA3QVqDU2kS
"""

import numpy as np
import pandas as pd

data = pd.read_csv("mpg.csv")
data

data['cylinders'].unique()

data['model_year'].value_counts()

data.groupby(['model_year','cylinders']).mean()

data.groupby('model_year').describe().transpose()

c= data.groupby(['model_year','cylinders']).mean()
c

"""Describing specific year"""

c.loc[[70,78]]

c

three_cylinder = c.xs(key = 3,level='cylinders')
three_cylinder

data.agg({'mpg':['mean','max'],'weight':['std','min']}  )

"""Combining Data"""

one = {'A':[1,2,3,4,],'B':[6,7,8,9],'C':[0,1,3,-4]}
two = {'D':[45,67,34,54,],'E':[16,47,58,91],'F':[120,31,63,-64]}

two = pd.DataFrame(two)
two

one = pd.DataFrame(one)
one

pd.concat([one,two] ,axis = 1)

pd.concat([one,two] ,axis = 0)

"""This solve problem of repeating"""

one.columns = two.columns

c = pd.concat([one,two])

c

c.index



c.index= range(len(c))
c

registrations = pd.DataFrame({'reg_id':[1,2,3,4],'name':['Andrew','Bobo','Claire','David']})
logins = pd.DataFrame({'log_id':[1,2,3,4],'name':['Xavier','Andrew','Yolanda','Bobo']})

registrations

logins

pd.merge(logins,registrations, how = 'inner' , on = 'name')

pd.merge(left=logins,right = registrations, how = 'left' , on = 'name')

"""Everything in right table should be dispalay"""

pd.merge(left=logins,right = registrations, how = 'right' , on = 'name')

email = "darwish@gmail.com"

email.split('@')

messy_names = pd.Series(["andrew  ","bo;bo","  claire  "])

messy_names

c= messy_names.str.replace(';','')
c

c2=c.str.capitalize()
c2